---
openapi: "3.0.1"
paths:
  /simple.SimpleService/DoSomething:
    post:
      summary: "Do Something"
      operationId: "simple.SimpleService.DoSomething"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/simple.SomeInput"
          application/protobuf:
            schema:
              type: "object"
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/simple.SomeOutput"
            application/protobuf:
              schema:
                type: "object"
components:
  schemas:
    simple.InputEnum:
      type: "string"
      enum:
      - "VAL1"
      - "VAL2"
      - "VAL3"
    simple.SomeInput:
      type: "object"
      properties:
        anotherField:
          type: "string"
          format: "string"
        someField:
          type: "string"
          format: "string"
        enumField:
          $ref: "#/components/schemas/simple.InputEnum"
    simple.SomeOutput.SomeEnum:
      type: "string"
      enum:
      - "FOO"
      - "BAR"
    simple.SomeOutput:
      type: "object"
      properties:
        enumOut:
          $ref: "#/components/schemas/simple.SomeOutput.SomeEnum"
        yetAnotherField:
          type: "string"
          format: "string"
