---
openapi: "3.0.1"
paths:
  /simple.SimpleService/DoSomething:
    post:
      summary: "Do Something"
      operationId: "simple.SimpleService.DoSomething"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/SomeInput"
          application/protobuf:
            schema:
              type: "object"
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SomeOutput"
            application/protobuf:
              schema:
                type: "object"
components:
  schemas:
    SomeInput:
      type: "object"
      properties:
        anotherField:
          type: "string"
          format: "string"
        someField:
          type: "string"
          format: "string"
    SomeOutput:
      type: "object"
      properties:
        yetAnotherField:
          type: "string"
          format: "string"
